### ISSUE TITLE
Select form field's options which able to filter by another select form field's value

### ISSUE THREAD

**Issue by zeskysee** [kctang/ng-quick-form#1]
I need to create a select form field's option which will filter by another form field's value.

Example:

2 select form field

- Country: Malaysia | Singapore
- State: `<options depend on country value>`

After the user selects Malaysia as the country. State form field should only show Malaysia's states as it options.

```
data = [ 
    { country: 'Malaysia', state: 'Selangor' },
    { country: 'Malaysia', state: 'Kuala Lumpur' },
    { country: 'Singapore', state: 'Singapore' }
]
```

**Comment by kctang** [comment]
sounds like a useful feature! :-)

**Comment by kctang** [comment]
Would it cover your requirements if we made changes to QuickFormField where `options` is updated to support being specified as a callback function that receives form values and is expected to return the actual options?


```
options?: QuickFormFieldOptionDefinition[] | ((formValues: any) => QuickFormFieldOptionDefinition[])

/**
 * Supported form field option definition styles.
 */
export type QuickFormFieldOptionDefinition = (
  string |
  { value: any, label: string } |
  { group: string, options: string[] } |
  { group: string, options: { value: any, label: string }[] }
  )
```

**Comment by zeskysee** [comment]
Sound good!
